feat: deploy to static app - standalone - remove slotName

diff --git a/.pipelines/app/templates/deployStaticApp.yml b/.pipelines/app/templates/deployStaticApp.yml
--- a/.pipelines/app/templates/deployStaticApp.yml
+++ b/.pipelines/app/templates/deployStaticApp.yml
@@ -70,11 +70,19 @@ jobs:
                     inlineScript: |
                       APIKEY=$(az staticwebapp secrets list --resource-group $(resourceGroupName) --name $(resourceGroupName)-site | jq -r '.properties.apiKey')
                       deployedAppUrl=$(az staticwebapp show --name $(resourceGroupName)-site | jq -r '.defaultHostname')
+
                       if test -z "$APIKEY" 
                       then
                         echo "##vso[task.logissue type=error]Unable to locate azure resource"
                         exit 1
                       fi
+
+                      if test -z "$deployedAppUrl" 
+                      then
+                        echo "##vso[task.logissue type=error]Unable to locate deployed app url"
+                        exit 1
+                      fi
+
                       echo "##vso[task.setvariable variable=apiKey;issecret=true]$APIKEY"
                       echo "##vso[task.setvariable variable=deployedBuildNumber;isOutput=true;]$(ciBuildNumber)"
                       echo "##vso[task.setvariable variable=deployedAppUrl;isOutput=true;]https://$deployedAppUrl"
